# Generated by Django 4.1.2 on 2022-10-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artiste_age_song_artiste_song_artiste_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
        migrations.AddField(
            model_name='lyric',
            name='Song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
